version: "3.8"
services:
  db:
    container_name: postgres-projects
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wassim
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projects
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
