version: "3.8"
services:
  db:
    container_name: postgres-projects
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: wassim
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projects
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
